---
title: "Cherry cultivar / chilling evaluation - PUCV - analysis report"
output: 
  html_document:
    highlight: tango
    toc: true
    toc_float:
        collapsed: false
    header-includes:
     - \usepackage{amsmath}
---




```{r, include=FALSE,echo=FALSE}
require(ggplot2)
require(magrittr)
require(dplyr)
require(reshape)
require(brms)
require(cowplot)
require(plotly)
require(rethinking)
require(gridExtra)
require(knitr)


d <- read.csv("../datafiles/Raw_combined_excel.csv")
e <- read.csv("../datafiles/Summary_stats.csv")

load("../modelfits/Bing_3p_updated")
Bi.post <- extract.samples(fit.test)
load("../modelfits/Kordia (C )_3p_updated")
KoC.post <- extract.samples(fit.test)
load("../modelfits/Kordia (M)_3p_updated")
KoM.post <- extract.samples(fit.test)
load("../modelfits/Lapins_3p_updated")
La.post <- extract.samples(fit.test)
load("../modelfits/Rainier_3p_updated")
Ra.post <- extract.samples(fit.test)
load("../modelfits/Regina_3p_updated")
Re.post <- extract.samples(fit.test)
load("../modelfits/Santina_3p_updated")
Sa.post <- extract.samples(fit.test)
load("../modelfits/Skeena_3p_updated")
Sk.post <- extract.samples(fit.test)
load("../modelfits/Sweetheart_3p_updated")
Sw.post <- extract.samples(fit.test)
```



# Slide 0: All active buds - means

```{r, echo=FALSE, message=FALSE, warning=FALSE}
  d %>% filter(week==3) %>% 
  group_by(variety,chill) %>% 
  summarise(mean = mean(prop)*100, 
            se = (1.96*sd(prop))/sqrt(12)*100) %>%
  ggplot(aes(chill, mean, ymin = mean-se, ymax = mean+se)) +
  geom_pointrange()  +
  labs(x="Variety", y="Mean + 95% CI of percent active buds (week 3)") +
  facet_wrap(~variety ) +
  theme_bw() +
  ggtitle("Week 3")
```


# Slide 1: Raw data plots

```{r, echo=FALSE, message=FALSE, warning=FALSE}

tempdf <- melt(d, measure=colnames(d)[c(6:20)]) %>% 
  na.omit(CP) %>%
  mutate(value = as.integer(value + 1),
         bud_u = as.factor(paste0(tree_u,variable)))

mod  <- tempdf %>% 
  group_by(variety, CP, bud_u) %>% 
  filter(value == 1) %>%
  summarise(min = max(GDH), 
            count = length(GDH)) %>% 
  group_by(variety,CP) %>% 
  summarise(mean = mean(min), 
            sd = sd(min),
            meanl = mean(ifelse(count==5,0,1))*100,
            sdl = sd(ifelse(count==5,0,1))*100)


ggplot(mod, aes(x=CP)) + 
  geom_line(aes(y=mean)) + 
  geom_ribbon(aes(ymin=mean-sd, ymax=mean+sd), alpha=.1) +
  geom_line(stat="identity", aes(y=meanl*50), linetype="dashed") +
  geom_ribbon(aes(ymin=(meanl-sdl)*50, ymax=(meanl+sdl)*50), alpha=.1) + 
  scale_y_continuous(sec.axis = sec_axis(~./50, breaks=c(0,100)))+
  theme_bw()+
  facet_wrap(~variety) +
  labs(x="Chilling Portions", y="Growing degree hours")

```

# Slide 2: example plot to overlay guide


```{r, echo=FALSE, message=FALSE, warning=FALSE}

mod  <- tempdf %>% 
  group_by(variety,CP, bud_u) %>% 
  filter(value == 1, variety=="Bing") %>%
  summarise(min = max(GDH), 
            count = length(GDH)) %>% 
  group_by(CP) %>% 
  summarise(mean = mean(min), 
            sd = sd(min),
            meanl = mean(ifelse(count==5,0,1))*100,
            sdl = sd(ifelse(count==5,0,1))*100)


ggplot(mod, aes(x=CP)) + 
  geom_line(aes(y=mean)) + 
  geom_ribbon(aes(ymin=mean-sd, ymax=mean+sd), alpha=.1) +
  geom_line(stat="identity", aes(y=meanl*50), linetype="dashed") +
  geom_ribbon(aes(ymin=(meanl-sdl)*50, ymax=(meanl+sdl)*50), alpha=.1) + 
  scale_y_continuous(sec.axis = sec_axis(~./50, breaks=c(0,100))) +
  labs(x="Chilling Portions", y="Growing degree hours")+
  theme_bw()

```


# Slide 3: minimum CP required to reach 50% budbreak at 21 days in greenhouse - raw data summary

```{r, echo=FALSE, message=FALSE, warning=FALSE}
te <- d %>% filter(week==3 & prop >= .5) %>% 
  group_by(variety, tree,sub) %>% 
  summarise(min(CP)) %>%
  group_by(variety) %>%
  summarise(mean = mean(`min(CP)`),
            sd = sd(`min(CP)`),
            length = length(`min(CP)`),
            sem = sd*1.96/sqrt(length))

ggplot(te, aes(variety, mean, ymin = mean-sem, ymax = mean+sem)) +
  geom_pointrange() +
  theme_bw() +
  labs(x="Variety", y="Mean + 95% CI minimum CP\n to reach 50% bud activity at 3 weeks")

bb_data <- te

```

# Slide 3b: minimum CH required to reach 50% budbreak at 21 days in greenhouse - raw data summary

```{r, echo=FALSE, message=FALSE, warning=FALSE}
g <- read.csv("../test/Raw_combined_excel_chours.csv")

te <- g %>% filter(week==3 & prop >= .5) %>% 
  group_by(variety, tree,sub) %>% 
  summarise(min(CP)) %>%
  group_by(variety) %>%
  summarise(mean = mean(`min(CP)`),
            sd = sd(`min(CP)`),
            length = length(`min(CP)`),
            sem = sd*1.96/sqrt(length))

ggplot(te, aes(variety, mean, ymin = mean-sem, ymax = mean+sem)) +
  geom_pointrange() +
  theme_bw() +
  labs(x="Variety", y="Mean + 95% CI minimum CH\n to reach 50% bud activity at 3 weeks")

bb_data_ch <- te

```


# Slide 3c: minimum CH required to reach 50% budbreak at 21 days in greenhouse - raw data summary

```{r, echo=FALSE, message=FALSE, warning=FALSE}
g <- read.csv("../test/Raw_combined_excel_cunits.csv")

te <- g %>% filter(week==3 & prop >= .5) %>% 
  group_by(variety, tree,sub) %>% 
  summarise(min(CP)) %>%
  group_by(variety) %>%
  summarise(mean = mean(`min(CP)`),
            sd = sd(`min(CP)`),
            length = length(`min(CP)`),
            sem = sd*1.96/sqrt(length))

ggplot(te, aes(variety, mean, ymin = mean-sem, ymax = mean+sem)) +
  geom_pointrange() +
  theme_bw() +
  labs(x="Variety", y="Mean + 95% CI minimum CH\n to reach 50% bud activity at 3 weeks")

bb_data_cu <- te

```
