---
title: "Table_maker"
author: "Graeme Baird"
date: "6/8/2018"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}

library(pander)
library(brms)
library(magrittr)
library(pander)
library(tidybayes)
d <- read.csv("../datafiles/Raw_combined_excel.csv")
varlist <- unique(d$variety)


```


```{r}
i = 1

  load(paste0("../modelfits/",varlist[i],"_3p_updated"))
  fit.test %>%
  gather_samples(`b_alpha[1]`, b_beta, b_eta, `temp_Intercept[1]`, `temp_Intercept[2]`, `Ysat`) %>% 
  mean_qi() %>%
  pander

```

```{r}
i = 2

  load(paste0("../modelfits/",varlist[i],"_3p_updated"))
  fit.test %>%
  gather_samples(`b_alpha[1]`, b_beta, b_eta, `temp_Intercept[1]`, `temp_Intercept[2]`, `Ysat`) %>% 
  mean_qi() %>%
  pander

```

```{r}
i = 3

  load(paste0("../modelfits/",varlist[i],"_3p_updated"))
  fit.test %>%
  gather_samples(`b_alpha[1]`, b_beta, b_eta, `temp_Intercept[1]`, `temp_Intercept[2]`, `Ysat`) %>% 
  mean_qi() %>%
  pander

```

```{r}
i = 4

  load(paste0("../modelfits/",varlist[i],"_3p_updated"))
  fit.test %>%
  gather_samples(`b_alpha[1]`, b_beta, b_eta, `temp_Intercept[1]`, `temp_Intercept[2]`, `Ysat`) %>% 
  mean_qi() %>%
  pander

```

```{r}
i = 5

  load(paste0("../modelfits/",varlist[i],"_3p_updated"))
  fit.test %>%
  gather_samples(`b_alpha[1]`, b_beta, b_eta, `temp_Intercept[1]`, `temp_Intercept[2]`, `Ysat`) %>% 
  mean_qi() %>%
  pander

```

```{r}
i = 6

  load(paste0("../modelfits/",varlist[i],"_3p_updated"))
  fit.test %>%
  gather_samples(`b_alpha[1]`, b_beta, b_eta, `temp_Intercept[1]`, `temp_Intercept[2]`, `Ysat`) %>% 
  mean_qi() %>%
  pander

```

```{r}
i = 7

  load(paste0("../modelfits/",varlist[i],"_3p_updated"))
  fit.test %>%
  gather_samples(`b_alpha[1]`, b_beta, b_eta, `temp_Intercept[1]`, `temp_Intercept[2]`, `Ysat`) %>% 
  mean_qi() %>%
  pander

```

```{r}
i = 8

  load(paste0("../modelfits/",varlist[i],"_3p_updated"))
  fit.test %>%
  gather_samples(`b_alpha[1]`, b_beta, b_eta, `temp_Intercept[1]`, `temp_Intercept[2]`, `Ysat`) %>% 
  mean_qi() %>%
  pander

```

```{r}
i = 9

  load(paste0("../modelfits/",varlist[i],"_3p_updated"))
  fit.test %>%
  gather_samples(`b_alpha[1]`, b_beta, b_eta, `temp_Intercept[1]`, `temp_Intercept[2]`, `Ysat`) %>% 
  mean_qi() %>%
  pander

```

```{r}
for(i in 1:9) {
  
  load(paste0("modelfits/",varlist[i],"_3p_updated"))
  fit.test %>% 
    posterior_samples %$% 
    quantile(Ysat*14.3562,c(.025,.5,.975)) %>%
    print()
  print(varlist[i])
}
```

